@startuml

actor 利用者A
actor 利用者B

usecase 今の気分を登録する as UC1
usecase 読んだ本を登録する as UC2
usecase 読んだ本はどの気分の時に読むと良さそうかを登録する as UC3


利用者A --> UC1
利用者B --> UC1

利用者A --> UC2
利用者B --> UC2


@enduml

---

@startuml

object 本 {
	isbn
}

object 利用者 {
	名前
}

object 性格

object 今の気分

object 興味のある分野

object どんな気分の時に読むと良いか {
}

object 読んだ本 {
}

object おすすめ本

object 分野
object 気分

利用者 "0..*"--"1..*" 読んだ本
利用者 -- 性格
利用者 -- 今の気分
利用者 -- 興味のある分野
読んだ本 -- どんな気分の時に読むと良いか
本 -- 読んだ本
本 -- おすすめ本

@enduml