
object 本 {
	isbn
}

object 利用者 {
	名前
}

object 性格

object 興味のある分野

object どんな気分の時に読むと良いか {
}

object 読んだ本 {
}

object おすすめ本

object 分野

利用者 "0..*"--"1..*" 読んだ本
利用者 -- 性格
読んだ本 -- どんな気分の時に読むと良いか
本 -- 読んだ本
本 -- おすすめ本